Update README.md
GuardianUI/guardianui-documentation pull request #2
Opened 2023-05-14 20:19 UTC by lipmaneth

Suggestions for docs

2023-05-15 19:16 UTC, 0xLienid commented on README.md
> +Our mission is simple. We aim to reduce the risk to users and teams that choose to partake in the crypto space. Improving testing and monitoring tooling is the primary focus at the moment.
"We aim to reduce the risk to users and teams that choose to partake in the crypto space face." would be better

2023-05-15 19:16 UTC, 0xLienid commented on api/gui.md
> +* `amount` - The amount to be approve to be spent by the spender. This needs to have the appropriate number of decimals (i.e. 1 ETH is "1000000000000000000")
approved

2023-05-15 19:17 UTC, 0xLienid commented on end-to-end-testing/writing-your-first-e2e-test.md
> +There are eight phases to writing your first e2e test using GuardianTest:
capitalize E2E

2023-05-15 19:21 UTC, 0xLienid requested changes
couple small bits of feedback

2023-05-16 02:25 UTC, lipmaneth commented
@0xLienid believe I've addressed your comments.

2023-05-23 00:52 UTC, closed without merging

2023-05-23 00:52 UTC, lipmaneth commented
Changes were done in gitbook. This is now old.